//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroMap.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgroMap.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available inspections.
        /// </summary>
        internal static string AvailableInspections {
            get {
                return ResourceManager.GetString("AvailableInspections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agromapproject.
        /// </summary>
        internal static string AWS_BUCKET_NAME {
            get {
                return ResourceManager.GetString("AWS_BUCKET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to us-east-2:65688d83-bb43-4a82-80fd-56de0731d99e.
        /// </summary>
        internal static string AWS_COGNITO_POOL_ID {
            get {
                return ResourceManager.GetString("AWS_COGNITO_POOL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel sync.
        /// </summary>
        internal static string CancelSync {
            get {
                return ResourceManager.GetString("CancelSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save the photo.
        /// </summary>
        internal static string CannotSavePhoto {
            get {
                return ResourceManager.GetString("CannotSavePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot sync with server.
        /// </summary>
        internal static string CannotSync {
            get {
                return ResourceManager.GetString("CannotSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        internal static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        internal static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created with success.
        /// </summary>
        internal static string CreatedWithSuccess {
            get {
                return ResourceManager.GetString("CreatedWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials. Verify your email and password.
        /// </summary>
        internal static string CredentialsError {
            get {
                return ResourceManager.GetString("CredentialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        internal static string Datetime {
            get {
                return ResourceManager.GetString("Datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection deleted with success.
        /// </summary>
        internal static string DeletedInspection {
            get {
                return ResourceManager.GetString("DeletedInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit inspection.
        /// </summary>
        internal static string EditInspection {
            get {
                return ResourceManager.GetString("EditInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required.
        /// </summary>
        internal static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends on.
        /// </summary>
        internal static string EndsOn {
            get {
                return ResourceManager.GetString("EndsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while getting data from sever. Try again.
        /// </summary>
        internal static string ErrorDeviceUUID {
            get {
                return ResourceManager.GetString("ErrorDeviceUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert photo from gallery.
        /// </summary>
        internal static string InsertPhoto {
            get {
                return ResourceManager.GetString("InsertPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection.
        /// </summary>
        internal static string Inspection {
            get {
                return ResourceManager.GetString("Inspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Kind {
            get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last edit at.
        /// </summary>
        internal static string Last_Edit_At {
            get {
                return ResourceManager.GetString("Last_Edit_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Last_name {
            get {
                return ResourceManager.GetString("Last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last sync on: .
        /// </summary>
        internal static string LastSyncOn {
            get {
                return ResourceManager.GetString("LastSyncOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing data from local storage.
        /// </summary>
        internal static string LoadedFromLocal {
            get {
                return ResourceManager.GetString("LoadedFromLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location found.
        /// </summary>
        internal static string LocationFound {
            get {
                return ResourceManager.GetString("LocationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still looking for location. Please wait..
        /// </summary>
        internal static string LocationNotFound {
            get {
                return ResourceManager.GetString("LocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location permission not granted..
        /// </summary>
        internal static string LocationNotGranted {
            get {
                return ResourceManager.GetString("LocationNotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be the creator of this event or supervisor of this inspection..
        /// </summary>
        internal static string MustBeCreatorOrSupervisor {
            get {
                return ResourceManager.GetString("MustBeCreatorOrSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be the supervisor of this inspection to manage it.
        /// </summary>
        internal static string MustBeSupervisor {
            get {
                return ResourceManager.GetString("MustBeSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New inspection.
        /// </summary>
        internal static string NewInspection {
            get {
                return ResourceManager.GetString("NewInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not synced.
        /// </summary>
        internal static string NotSync {
            get {
                return ResourceManager.GetString("NotSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        internal static string Observation {
            get {
                return ResourceManager.GetString("Observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        internal static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agromapproject.
        /// </summary>
        internal static string S3_Bucket {
            get {
                return ResourceManager.GetString("S3_Bucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching location....
        /// </summary>
        internal static string SearchingLocation {
            get {
                return ResourceManager.GetString("SearchingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ServerBackup2 {
            get {
                return ResourceManager.GetString("ServerBackup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/inspection/create-event.
        /// </summary>
        internal static string ServerURICreateEvent {
            get {
                return ResourceManager.GetString("ServerURICreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/inspection/create-events.
        /// </summary>
        internal static string ServerURICreateEvents {
            get {
                return ResourceManager.GetString("ServerURICreateEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/inspection/create.
        /// </summary>
        internal static string ServerURICreateInspection {
            get {
                return ResourceManager.GetString("ServerURICreateInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/inspection/delete.
        /// </summary>
        internal static string ServerURIDeleteInspection {
            get {
                return ResourceManager.GetString("ServerURIDeleteInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/inspection/get-event-by-id/.
        /// </summary>
        internal static string ServerURIEventById {
            get {
                return ResourceManager.GetString("ServerURIEventById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/inspection/get-event-by-inspection/.
        /// </summary>
        internal static string ServerURIEventByInspection {
            get {
                return ResourceManager.GetString("ServerURIEventByInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/inspection/get-event-by-user/.
        /// </summary>
        internal static string ServerURIEventByUser {
            get {
                return ResourceManager.GetString("ServerURIEventByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/inspection/get-uuid.
        /// </summary>
        internal static string ServerURIGetUUID {
            get {
                return ResourceManager.GetString("ServerURIGetUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/inspection/get-all.
        /// </summary>
        internal static string ServerURIInspectionAll {
            get {
                return ResourceManager.GetString("ServerURIInspectionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/inspection/get-by-id/.
        /// </summary>
        internal static string ServerURIInspectionById {
            get {
                return ResourceManager.GetString("ServerURIInspectionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/inspection/get-by-supervisor/.
        /// </summary>
        internal static string ServerURIInspectionBySupervisor {
            get {
                return ResourceManager.GetString("ServerURIInspectionBySupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/inspection/get-by-user/.
        /// </summary>
        internal static string ServerURIInspectionByUser {
            get {
                return ResourceManager.GetString("ServerURIInspectionByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/user/signin.
        /// </summary>
        internal static string ServerURISignin {
            get {
                return ResourceManager.GetString("ServerURISignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/user/signup.
        /// </summary>
        internal static string ServerURISignup {
            get {
                return ResourceManager.GetString("ServerURISignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/inspection/update.
        /// </summary>
        internal static string ServerURIUpdateInspection {
            get {
                return ResourceManager.GetString("ServerURIUpdateInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://agromap.herokuapp.com/.
        /// </summary>
        internal static string ServerURL {
            get {
                return ResourceManager.GetString("ServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://agromap.herokuapp.com/.
        /// </summary>
        internal static string ServerURLBackup {
            get {
                return ResourceManager.GetString("ServerURLBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on map.
        /// </summary>
        internal static string ShowOnMap {
            get {
                return ResourceManager.GetString("ShowOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signin.
        /// </summary>
        internal static string Signin {
            get {
                return ResourceManager.GetString("Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        internal static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronize.
        /// </summary>
        internal static string Sincronize {
            get {
                return ResourceManager.GetString("Sincronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts on.
        /// </summary>
        internal static string StartOn {
            get {
                return ResourceManager.GetString("StartOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created! Once approved by an admin, you can login.
        /// </summary>
        internal static string SuccessSignup {
            get {
                return ResourceManager.GetString("SuccessSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        internal static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing.
        /// </summary>
        internal static string Syncing {
            get {
                return ResourceManager.GetString("Syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order, to manage inspections, a internet connection is required.
        /// </summary>
        internal static string ToManageInspection {
            get {
                return ResourceManager.GetString("ToManageInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Typeof {
            get {
                return ResourceManager.GetString("Typeof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with your data. Check your data and try again..
        /// </summary>
        internal static string UserDataError {
            get {
                return ResourceManager.GetString("UserDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id.
        /// </summary>
        internal static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum length of name is 3 characters. The start date must be equal or higher than current date and the end date must be higher than start date..
        /// </summary>
        internal static string VerifyFieldsInspection {
            get {
                return ResourceManager.GetString("VerifyFieldsInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More at: github.com/eraldojr/agromap.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        internal static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
    }
}
